theme: jekyll-theme-modernist
title: Altspace LGBTQ+ Homepage
description: We have created this space for those who have difficulty sharing their thoughts and experiences.
url: https://vrlgbtqmeetup.github.io/